#!/bin/sh
#export GIT_AUTHOR_NAME=$PLUGIN_GIT_USER_NAME
GIT_AUTHOR_NAME=nataliavr
#export GIT_AUTHOR_EMAIL=$PLUGIN_GIT_USER_EMAIL
GIT_AUTHOR_EMAIL=natali@coognitive.com
#export GIT_COMMITTER_NAME=$PLUGIN_GIT_USER_NAME
GIT_COMMITTER_NAME=nataliavr
#export GIT_COMMITTER_EMAIL=$PLUGIN_GIT_USER_EMAIL
GIT_COMMITTER_EMAIL=natali@coognitive.com
#export GH_TOKEN=$PLUGIN_GITHUB_TOKEN
#export GH_REPO=$PLUGIN_GITHUB_REPO
GH_REPO=nataliavr/test.git
#export VERSION_TYPE=$PLUGIN_VERSION_TYPE
VERSION_TYPE=patch

release-it --no-npm.publish $VERSION_TYPE --github.release --no-git.requireUpstream --ci
